// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI_EX1_DAY30.Models;

#nullable disable

namespace WebAPI_EX1_DAY30.Migrations
{
    [DbContext(typeof(ProductsDbContext))]
    partial class ProductsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPI_EX1_DAY30.Models.CompanyInfo", b =>
                {
                    b.Property<int>("Cid")
                        .HasColumnType("int")
                        .HasColumnName("CId");

                    b.Property<string>("Cname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CName");

                    b.HasKey("Cid")
                        .HasName("PK__CompanyI__C1F8DC39EA77E54C");

                    b.ToTable("CompanyInfo", (string)null);
                });

            modelBuilder.Entity("WebAPI_EX1_DAY30.Models.ProductInfo", b =>
                {
                    b.Property<int>("Pid")
                        .HasColumnType("int")
                        .HasColumnName("PId");

                    b.Property<int?>("Cid")
                        .HasColumnType("int")
                        .HasColumnName("CId");

                    b.Property<DateTime?>("Pmdate")
                        .HasColumnType("date")
                        .HasColumnName("PMDate");

                    b.Property<string>("Pname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PName");

                    b.Property<double?>("Pprice")
                        .HasColumnType("float")
                        .HasColumnName("PPrice");

                    b.HasKey("Pid")
                        .HasName("PK__ProductI__C577554057EAAFB5");

                    b.HasIndex("Cid");

                    b.ToTable("ProductInfo", (string)null);
                });

            modelBuilder.Entity("WebAPI_EX1_DAY30.Models.ProductInfo", b =>
                {
                    b.HasOne("WebAPI_EX1_DAY30.Models.CompanyInfo", "CidNavigation")
                        .WithMany("ProductInfos")
                        .HasForeignKey("Cid")
                        .HasConstraintName("FK__ProductInfo__CId__398D8EEE");

                    b.Navigation("CidNavigation");
                });

            modelBuilder.Entity("WebAPI_EX1_DAY30.Models.CompanyInfo", b =>
                {
                    b.Navigation("ProductInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
